import type { EventPublisher } from '../application/ports/event-publisher.js';
import type { DepositMonitorRepository } from '../application/ports/deposit-monitor-repository.js';
import { DepositMonitorService } from '../application/services/deposit-monitor-service.js';
import { DepositMonitorWorker } from '../application/services/deposit-monitor-worker.js';
import { ActivationGrantService } from '../application/services/activation-grant-service.js';
import { ActivationGrantWorker } from '../application/services/activation-grant-worker.js';
import { ActivationReclaimService } from '../application/services/activation-reclaim-service.js';
import { ActivationReclaimWorker } from '../application/services/activation-reclaim-worker.js';
import { ResourceDelegationService } from '../application/services/resource-delegation-service.js';
import { ResourceDelegationWorker } from '../application/services/resource-delegation-worker.js';
import { AlertService } from '../application/services/alert-service.js';
import { AlertWorker } from '../application/services/alert-worker.js';
import type { WithdrawJobQueue } from '../application/ports/withdraw-job-queue.js';
import { AccountReconciliationService } from '../application/services/account-reconciliation-service.js';
import { ExternalAlertMonitorService } from '../application/services/external-alert-monitor-service.js';
import { ExternalAlertMonitorWorker } from '../application/services/external-alert-monitor-worker.js';
import { MonitoringWorker } from '../application/services/monitoring-worker.js';
import type { LedgerRepository } from '../application/ports/ledger-repository.js';
import type { AlertMonitorStateRepository } from '../application/ports/alert-monitor-state-repository.js';
import { SystemMonitoringService } from '../application/services/system-monitoring-service.js';
import { DepositService } from '../application/services/deposit-service.js';
import { OnchainService } from '../application/services/onchain-service.js';
import { SchedulerService } from '../application/services/scheduler-service.js';
import { OperationsService } from '../application/services/operations-service.js';
import { SweepBotService } from '../application/services/sweep-bot-service.js';
import { SweepBotWorker } from '../application/services/sweep-bot-worker.js';
import { VirtualWalletLifecyclePolicyService } from '../application/services/virtual-wallet-lifecycle-policy-service.js';
import { VirtualWalletService } from '../application/services/virtual-wallet-service.js';
import { WalletService } from '../application/services/wallet-service.js';
import { WithdrawDispatchWorker } from '../application/services/withdraw-dispatch-worker.js';
import { WithdrawGuardService } from '../application/services/withdraw-guard-service.js';
import { WithdrawPolicyService } from '../application/services/withdraw-policy-service.js';
import { WithdrawService } from '../application/services/withdraw-service.js';

export interface AppDependencies {
  ledger: LedgerRepository;
  depositMonitorRepository: DepositMonitorRepository;
  alertMonitorStateRepository: AlertMonitorStateRepository;
  eventPublisher: EventPublisher;
  alertService: AlertService;
  withdrawJobQueue: WithdrawJobQueue;
  activationGrantService: ActivationGrantService;
  activationGrantWorker: ActivationGrantWorker;
  activationReclaimService: ActivationReclaimService;
  activationReclaimWorker: ActivationReclaimWorker;
  resourceDelegationService: ResourceDelegationService;
  resourceDelegationWorker: ResourceDelegationWorker;
  externalAlertMonitorService: ExternalAlertMonitorService;
  externalAlertMonitorWorker: ExternalAlertMonitorWorker;
  systemMonitoringService: SystemMonitoringService;
  onchainService: OnchainService;
  depositMonitorService: DepositMonitorService;
  depositMonitorWorker: DepositMonitorWorker;
  sweepBotService: SweepBotService;
  sweepBotWorker: SweepBotWorker;
  monitoringWorker: MonitoringWorker;
  alertWorker: AlertWorker;
  depositService: DepositService;
  virtualWalletService: VirtualWalletService;
  virtualWalletLifecyclePolicy: VirtualWalletLifecyclePolicyService;
  walletService: WalletService;
  accountReconciliationService: AccountReconciliationService;
  withdrawPolicyService: WithdrawPolicyService;
  withdrawGuardService: WithdrawGuardService;
  withdrawService: WithdrawService;
  withdrawDispatchWorker: WithdrawDispatchWorker;
  schedulerService: SchedulerService;
  operationsService: OperationsService;
}
